### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: BridgingCreator not initialized

### ISSUE THREAD

**Issue by keyurgit45** [superwall/Superwall-Flutter#44]
Firebase crashlytics error log:

          Fatal Exception: java.lang.IllegalStateException: BridgingCreator not initialized
       at com.superwall.superwallkit_flutter.BridgingCreator$Companion.getShared(BridgingCreator.kt:24)
       at com.superwall.superwallkit_flutter.bridges.PaywallInfoBridgeKt.createBridgeId(PaywallInfoBridge.kt:62)
       at SuperwallEventInfo_JsonKt.toJson(SuperwallEventInfo+Json.kt:155)
       at SuperwallEventInfo_JsonKt.toJson(SuperwallEventInfo+Json.kt:9)
       at com.superwall.superwallkit_flutter.bridges.SuperwallDelegateProxyBridge.handleSuperwallEvent(SuperwallDelegateProxyBridge.kt:45)
       at com.superwall.sdk.delegate.SuperwallDelegateAdapter.handleSuperwallEvent(SuperwallDelegateAdapter.kt:48)
       at com.superwall.sdk.analytics.internal.TrackingKt$track$2.invokeSuspend(Tracking.kt:51)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:223)
       at android.os.Looper.loop(Looper.java:324)
       at android.app.ActivityThread.main(ActivityThread.java:8481)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1061)
       
flutter doctor --verbose

[✓] Flutter (Channel stable, 3.22.2, on Pop!_OS 22.04 LTS 6.9.3-76060903-generic, locale en_US.UTF-8)
    • Flutter version 3.22.2 on channel stable at /home/user/fvm/versions/3.22.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (6 months ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc3)
    • Android SDK at /home/user/Android/Sdk
    • Platform android-35, build-tools 35.0.0-rc3
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2024.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 82.1.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[✓] VS Code (version 1.95.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.102.0

We are experiencing frequent crashes with the latest release of Superwall. I am not able to reproduce the issue while debugging.

**Comment by ianrumac** [comment]
Hey @keyurgit45 ! Thanks for the report!
Our new version 1.3.5 should help mitigate the issue, but please don't hesitate to reopen the issue if you notice it show up again!

**Comment by royston-c** [comment]
Hi @ianrumac 

I am seeing this same error on Android device using superwallkit_flutter @ 2.0.0 

```
Fatal Exception: java.lang.IllegalStateException: BridgingCreator not initialized
       at com.superwall.superwallkit_flutter.BridgingCreator$Companion.getShared(BridgingCreator.java:11)
       at com.superwall.superwallkit_flutter.bridges.PaywallInfoBridgeKt.createBridgeId(PaywallInfoBridge.kt:56)
       at SuperwallEventInfo_JsonKt.toJson(SuperwallEventInfo_Json.kt:1965)
       at SuperwallEventInfo_JsonKt.a(SuperwallEventInfo_Json.kt:77)
       at com.superwall.superwallkit_flutter.bridges.SuperwallDelegateProxyBridge$handleSuperwallPlacement$1.invokeSuspend(SuperwallDelegateProxyBridge.java:70)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:8)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:109)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:17)
       at kotlinx.coroutines.scheduling.TaskImpl.run(TaskImpl.java:2)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:98)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:98)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:98)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:98)
        
```

The logs/timestamps for the 100+ users this has happened to suggest that this occurs when:

1. app is opened
2. left idle (most likely pushed to the background)
3. the app is used again between 10mins to a few hours later

**Comment by royston-c** [comment]
@ianrumac can this ticket be reopened, given the above?
