### ISSUE TITLE
Failed to configure Superwall: MissingPluginException

### ISSUE THREAD

**Issue by kamaravichow** [superwall/Superwall-Flutter#6]
Here are the logs

```
I/flutter (14729): Failed to configure Superwall: MissingPluginException(No implementation found for method createBridgeInstance on channel SWK_BridgingCreator)
E/flutter (14729): #1      BridgingCreator._invokeBridgeInstanceCreation (package:superwallkit_flutter/src/private/BridgingCreator.dart:28:5)
E/flutter (14729): #2      BridgingCreator._ensureBridgeCreated (package:superwallkit_flutter/src/private/BridgingCreator.dart:40:7)
E/flutter (14729): #3      BridgeAdditions.ensureBridgeCreated (package:superwallkit_flutter/src/private/BridgingCreator.dart:118:5)
E/flutter (14729): #4      MethodChannelBridging.invokeBridgeMethod (package:superwallkit_flutter/src/private/BridgingCreator.dart:69:11)
E/flutter (14729): #5      Superwall.setSubscriptionStatus (package:superwallkit_flutter/src/public/Superwall.dart:149:18)
E/flutter (14729): #1      BridgingCreator._invokeBridgeInstanceCreation (package:superwallkit_flutter/src/private/BridgingCreator.dart:28:5)
E/flutter (14729): #2      BridgingCreator._ensureBridgeCreated (package:superwallkit_flutter/src/private/BridgingCreator.dart:40:7)
E/flutter (14729): #3      BridgeAdditions.ensureBridgeCreated (package:superwallkit_flutter/src/private/BridgingCreator.dart:118:5)
E/flutter (14729): #4      MethodChannelBridging.invokeBridgeMethod (package:superwallkit_flutter/src/private/BridgingCreator.dart:69:11)
E/flutter (14729): #5      Superwall.setSubscriptionStatus (package:superwallkit_flutter/src/public/Superwall.dart:149:18)
E/flutter (14729): #1      BridgingCreator._invokeBridgeInstanceCreation (package:superwallkit_flutter/src/private/BridgingCreator.dart:28:5)
E/flutter (14729): #2      BridgingCreator._ensureBridgeCreated (package:superwallkit_flutter/src/private/BridgingCreator.dart:40:7)
E/flutter (14729): #3      BridgeAdditions.ensureBridgeCreated (package:superwallkit_flutter/src/private/BridgingCreator.dart:118:5)
E/flutter (14729): #4      MethodChannelBridging.invokeBridgeMethod (package:superwallkit_flutter/src/private/BridgingCreator.dart:69:11)
E/flutter (14729): #5      Superwall.setSubscriptionStatus (package:superwallkit_flutter/src/public/Superwall.dart:149:18)
E/flutter (14729): #1      BridgingCreator._invokeBridgeInstanceCreation (package:superwallkit_flutter/src/private/BridgingCreator.dart:28:5)
E/flutter (14729): #2      BridgingCreator._ensureBridgeCreated (package:superwallkit_flutter/src/private/BridgingCreator.dart:40:7)
E/flutter (14729): #3      BridgeAdditions.ensureBridgeCreated (package:superwallkit_flutter/src/private/BridgingCreator.dart:118:5)
E/flutter (14729): #4      MethodChannelBridging.invokeBridgeMethod (package:superwallkit_flutter/src/private/BridgingCreator.dart:69:11)
E/flutter (14729): #5      PublicPresentation.registerEvent (package:superwallkit_flutter/src/public/Superwall.dart:290:18)

```

**Comment by yusuftor** [comment]
Hey, I believe this is fixed in the latest version (v1.1.3). Please reopen if this issue still exists!
